### ISSUE TITLE
Results for haematology does not get published

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#180] opened 2019-01-21 08:20 UTC
## Steps to reproduce
https://github.com/bhp-lims/bhp.lims/issues/178

## Current behavior
Results for haematology does not get published

## Expected behavior
Results for haematology should be  published

**Comment by xispa** [comment] 2019-01-22 08:48
Duplicate of https://github.com/bhp-lims/bhp.lims/issues/178

**Closed by xispa** 2019-01-22 08:48 UTC
