### ISSUE TITLE
Allow scanning of analysis request when storing them

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#220] opened 2019-04-02 13:18 UTC
## Steps to reproduce
> Go to storage module
> select  container/facility
> select sample storage
> add sample to sample storage

## Current behavior
samples cannot be scanned when storing them, allows entering sample ID manually to store them

## Expected behavior
should allow samples to be scanned when storing them in samples container

**Comment by xispa** [comment] 2019-04-03 08:03
Duplicate of #210

**Closed by xispa** 2019-04-03 08:03 UTC
Labels: Bug, Storage
