### ISSUE TITLE
Results email comes with no attachment IMPACT 2010.

### ISSUE THREAD

**Issue by MoffatMore** [bhp-lims/bhp.lims#184] opened 2019-01-21 08:50 UTC
## Steps to reproduce
https://github.com/bhp-lims/bhp.lims/issues/178

## Current behavior
https://github.com/bhp-lims/bhp.lims/issues/178

## Expected behavior
Results email should come with  attachment from IMPACT 2010. study

**Comment by xispa** [comment] 2019-01-22 08:49
Duplicate of https://github.com/bhp-lims/bhp.lims/issues/178

**Closed by xispa** 2019-01-22 08:49 UTC
